var ramp=d3.scale.linear().domain([0,10,25]).range(["lightblue","blue", "#0000cd"]);

var basic_choropleth = new Datamap({
  element: document.getElementById("svg_map4"),
    scope: 'world',
    // Zoom in on Africa
    // setProjection: function(element) {
      // var projection = d3.geo.equirectangular()
        // .center([23, -3])
        //  .rotate([4.4, 0])
        //  .scale(400)
        //  .translate([element.offsetWidth / 2, element.offsetHeight / 2]);
      //  var path = d3.geo.path()
        //  .projection(projection);
      // return {path: path, projection: projection};
    // },
  element: document.getElementById("svg_map4"),
  projection: 'mercator',
  fills: {
    defaultFill: "#CCCCCC",
    AFG: ramp(4.2),
    ALB: ramp(0.1),
    DZA: ramp(4.9),
    AGO: ramp(10.9),
    ARG: ramp(0  ),
    ARM: ramp(0.3),
    AUS: ramp(0.0),
    AUT: ramp(0.0),
    AZE: ramp(0.1),
    BHS: ramp(0  ),
    BHR: ramp(0.1),
    BGD: ramp(1.1),
    BLR: ramp(0.1),
    BEL: ramp(0.1),
    BLZ: ramp(0  ),
    BEN: ramp(0  ),
    BTN: ramp(0.5),
    BOL: ramp(0  ),
    BIH: ramp(0.0),
    BWA: ramp(0.0),
    BRA: ramp(0.0),
    BGR: ramp(0.1),
    BFA: ramp(1.8),
    MMR: ramp(0.9),
    BDI: ramp(13.1),
    KHM: ramp(0.1),
    CMR: ramp(21.9),
    CAN: ramp(0.0),
    CAF: ramp(18.1),
    TCD: ramp(4.7),
    CHL: ramp(0.0),
    CHN: ramp(0.3),
    COL: ramp(7.6),
    COG: ramp(0.5),
    COD: ramp(10.6),
    CRI: ramp(0.0),
    HRV: ramp(0.0),
    CUB: ramp(0.0),
    CYP: ramp(0  ),
    CZE: ramp(0.0),
    DNK: ramp(0.0),
    DJI: ramp(0.1),
    DMA: ramp(0.1),
    DOM: ramp(0  ),
    TMP: ramp(0.1),
    ECU: ramp(0.0),
    EGY: ramp(1.0),
    GNQ: ramp(0.0),
    ERI: ramp(0.3),
    EST: ramp(0.0),
    ETH: ramp(1.9),
    FJI: ramp(0.2),
    FIN: ramp(0.0),
    FRA: ramp(0.1),
    GAB: ramp(0  ),
    GMB: ramp(0  ),
    GEO: ramp(0.1),
    DEU: ramp(0.0),
    GHA: ramp(0  ),
    GRC: ramp(0.1),
    GTM: ramp(0.3),
    GIN: ramp(0.8),
    GNB: ramp(0.1),
    GUY: ramp(1.3),
    HTI: ramp(0.2),
    HND: ramp(0.6),
    HKG: ramp(0  ),
    HUN: ramp(0.0),
    ISL: ramp(0  ),
    IND: ramp(3.5),
    IDN: ramp(0.9),
    IRN: ramp(0.1),
    IRQ: ramp(6.3),
    IRL: ramp(0.0),
    ISR: ramp(0.2),
    ITA: ramp(0.0),
    JAM: ramp(0  ),
    JPN: ramp(0.0),
    JOR: ramp(0.1),
    KAZ: ramp(0.2),
    KEN: ramp(1.6),
    KWT: ramp(0.1),
    KGZ: ramp(0.1),
    LAO: ramp(0.3),
    LVA: ramp(0.0),
    LBN: ramp(0.5),
    LSO: ramp(0.1),
    LBR: ramp(0.1),
    LBY: ramp(1.2),
    MKD: ramp(0.3),
    MDG: ramp(0.2),
    MWI: ramp(0.0),
    MYS: ramp(0.0),
    MDV: ramp(0  ),
    MLI: ramp(2.7),
    MLT: ramp(0  ),
    MRT: ramp(0.5),
    MEX: ramp(0.2),
    MDA: ramp(0.0),
    MAR: ramp(0.1),
    MOZ: ramp(1.3),
    NAM: ramp(1.0),
    NPL: ramp(14.3),
    NLD: ramp(0.0),
    NZL: ramp(0  ),
    NIC: ramp(0.0),
    NER: ramp(4.3),
    NGA: ramp(31.1),
    NOR: ramp(0.2),
    PAK: ramp(3.7),
    PAN: ramp(0.0),
    PNG: ramp(0  ),
    PRY: ramp(1.0),
    PER: ramp(0.9),
    PHL: ramp(7.8),
    POL: ramp(0),
    PRT: ramp(0),
    QAT: ramp(0.0),
    ROU: ramp(0),
    RUS: ramp(0.9),
    RWA: ramp(0.2),
    KNA: ramp(0.3),
    SAU: ramp(0.2),
    SEN: ramp(1.1),
    SRB: ramp(0.0),
    SLE: ramp(0.3),
    SVK: ramp(0),
    SVN: ramp(0),
    SLB: ramp(0.2),
    SOM: ramp(6.9),
    ZAF: ramp(0.1),
    ESP: ramp(0.1),
    LKA: ramp(6.9),
    SDN: ramp(3.9),
    SUR: ramp(1.0),
    SWZ: ramp(0),
    SWE: ramp(0.0),
    CHE: ramp(0.0),
    SYR: ramp(2.6),
    TWN: ramp(0.0),
    TJK: ramp(0.3),
    TZA: ramp(0.1),
    THA: ramp(5.7),
    TGO: ramp(0),
    TTO: ramp(0),
    TUN: ramp(0.5),
    TUR: ramp(1.0),
    TKM: ramp(0.0),
    UGA: ramp(4.8),
    UKR: ramp(2.9),
    ARE: ramp(0.0),
    GBR: ramp(0.1),
    USA: ramp(0.6),
    URY: ramp(0.0),
    UZB: ramp(0.2),
    VUT: ramp(0.1),
    VEN: ramp(0.1),
    VNM: ramp(0),
    ESH: ramp(0),
    YEM: ramp(4.8),
    ZMB: ramp(0.1),
    ZWE: ramp(0.0),
    SSD: ramp(19.9),
    PSE: ramp(0.5),


  },
  data: {
    AFG: { fillKey: "AFG", percentage:	"4.2"},
    ALB: { fillKey: "ALB", percentage:	"0.1"},
    DZA: { fillKey: "DZA", percentage:	"4.9"},
    AGO: { fillKey: "AGO", percentage:	"10.9"},
    ARG: { fillKey: "ARG", percentage: "0"},
    ARM: { fillKey: "ARM", percentage: "0.3"},
    AUS: { fillKey: "AUS", percentage: "0.0"},
    AUT: { fillKey: "AUT", percentage: "0.0"},
    AZE: { fillKey: "AZE", percentage: "0.1"},
    BHS: { fillKey: "BHS", percentage: "-"},
    BHR: { fillKey: "BHR", percentage: "0.1"},
    BGD: { fillKey: "BGD", percentage: "1.1"},
    BLR: { fillKey: "BLR", percentage: "0.1"},
    BEL: { fillKey: "BEL", percentage: "0.1"},
    BLZ: { fillKey: "BLZ", percentage: "-  "},
    BEN: { fillKey: "BEN", percentage: "-  "},
    BTN: { fillKey: "BTN", percentage: "0.5"},
    BOL: { fillKey: "BOL", percentage: "-  "},
    BIH: { fillKey: "BIH", percentage: "0.0"},
    BWA: { fillKey: "BWA", percentage: "0.0"},
    BRA: { fillKey: "BRA", percentage: "0.0"},
    BGR: { fillKey: "BGR", percentage: "0.1"},
    BFA: { fillKey: "BFA", percentage: "1.8"},
    MMR: { fillKey: "MMR", percentage: "0.9"},
    BDI: { fillKey: "BDI", percentage: "13.1"},
    KHM: { fillKey: "KHM", percentage: "0.1"},
    CMR: { fillKey: "CMR", percentage: "21.9"},
    CAN: { fillKey: "CAN", percentage: "0.0"},
    CAF: { fillKey: "CAF", percentage: "18.1"},
    TCD: { fillKey: "TCD", percentage: "4.7"},
    CHL: { fillKey: "CHL", percentage: "0.0"},
    CHN: { fillKey: "CHN", percentage: "0.3"},
    COL: { fillKey: "COL", percentage: "7.6"},
    COG: { fillKey: "COG", percentage: "0.5"},
    COD: { fillKey: "COD", percentage: "10.6"},
    CRI: { fillKey: "CRI", percentage: "0.0"},
    HRV: { fillKey: "HRV", percentage: "0.0"},
    CUB: { fillKey: "CUB", percentage: "0.0"},
    CYP: { fillKey: "CYP", percentage: "-  "},
    CZE: { fillKey: "CZE", percentage: "0.0"},
    DNK: { fillKey: "DNK", percentage: "0.0"},
    DJI: { fillKey: "DJI", percentage: "0.1"},
    DMA: { fillKey: "DMA", percentage: "0.1"},
    DOM: { fillKey: "DOM", percentage: "-  "},
    TMP: { fillKey: "TMP", percentage: "0.1"},
    ECU: { fillKey: "ECU", percentage: "0.0"},
    EGY: { fillKey: "EGY", percentage: "1.0"},
    GNQ: { fillKey: "GNQ", percentage: "0.0"},
    ERI: { fillKey: "ERI", percentage: "0.3"},
    EST: { fillKey: "EST", percentage: "0.0"},
    ETH: { fillKey: "ETH", percentage: "1.9"},
    FJI: { fillKey: "FJI", percentage: "0.2"},
    FIN: { fillKey: "FIN", percentage: "0.0"},
    FRA: { fillKey: "FRA", percentage: "0.1"},
    GAB: { fillKey: "GAB", percentage: "-  "},
    GMB: { fillKey: "GMB", percentage: "-  "},
    GEO: { fillKey: "GEO", percentage: "0.1"},
    DEU: { fillKey: "DEU", percentage: "0.0"},
    GHA: { fillKey: "GHA", percentage: "-  "},
    GRC: { fillKey: "GRC", percentage: "0.1"},
    GTM: { fillKey: "GTM", percentage: "0.3"},
    GIN: { fillKey: "GIN", percentage: "0.8"},
    GNB: { fillKey: "GNB", percentage: "0.1"},
    GUY: { fillKey: "GUY", percentage: "1.3"},
    HTI: { fillKey: "HTI", percentage: "0.2"},
    HND: { fillKey: "HND", percentage: "0.6"},
    HKG: { fillKey: "HKG", percentage: "-"},
    HUN: { fillKey: "HUN", percentage: "0.0"},
    ISL: { fillKey: "ISL", percentage: "-  "},
    IND: { fillKey: "IND", percentage: "3.5"},
    IDN: { fillKey: "IDN", percentage: "0.9"},
    IRN: { fillKey: "IRN", percentage: "0.1"},
    IRQ: { fillKey: "IRQ", percentage: "6.3"},
    IRL: { fillKey: "IRL", percentage: "0.0"},
    ISR: { fillKey: "ISR", percentage: "0.2"},
    ITA: { fillKey: "ITA", percentage: "0.0"},
    JAM: { fillKey: "JAM", percentage: "-  "},
    JPN: { fillKey: "JPN", percentage: "0.0"},
    JOR: { fillKey: "JOR", percentage: "0.1"},
    KAZ: { fillKey: "KAZ", percentage: "0.2"},
    KEN: { fillKey: "KEN", percentage: "1.6"},
    KWT: { fillKey: "KWT", percentage: "0.1"},
    KGZ: { fillKey: "KGZ", percentage: "0.1"},
    LAO: { fillKey: "LAO", percentage: "0.3"},
    LVA: { fillKey: "LVA", percentage: "0.0"},
    LBN: { fillKey: "LBN", percentage: "0.5"},
    LSO: { fillKey: "LSO", percentage: "0.1"},
    LBR: { fillKey: "LBR", percentage: "0.1"},
    LBY: { fillKey: "LBY", percentage: "1.2"},
    MKD: { fillKey: "MKD", percentage: "0.3"},
    MDG: { fillKey: "MDG", percentage: "0.2"},
    MWI: { fillKey: "MWI", percentage: "0.0"},
    MYS: { fillKey: "MYS", percentage: "0.0"},
    MDV: { fillKey: "MDV", percentage: "-  "},
    MLI: { fillKey: "MLI", percentage: "2.7"},
    MLT: { fillKey: "MLT", percentage: "-  "},
    MRT: { fillKey: "MRT", percentage: "0.5"},
    MEX: { fillKey: "MEX", percentage: "0.2"},
    MDA: { fillKey: "MDA", percentage: "0.0"},
    MAR: { fillKey: "MAR", percentage: "0.1"},
    MOZ: { fillKey: "MOZ", percentage: "1.3"},
    NAM: { fillKey: "NAM", percentage: "1.0"},
    NPL: { fillKey: "NPL", percentage: "14.3"},
    NLD: { fillKey: "NLD", percentage: "0.0"},
    NZL: { fillKey: "NZL", percentage: "-  "},
    NIC: { fillKey: "NIC", percentage: "0.0"},
    NER: { fillKey: "NER", percentage: "4.3"},
    NGA: { fillKey: "NGA", percentage: "31.1"},
    NOR: { fillKey: "NOR", percentage: "0.2"},
    PAK: { fillKey: "PAK", percentage: "3.7"},
    PAN: { fillKey: "PAN", percentage: "0.0"},
    PNG: { fillKey: "PNG", percentage: "-  "},
    PRY: { fillKey: "PRY", percentage: "1.0"},
    PER: { fillKey: "PER", percentage: "0.9"},
    PHL: { fillKey: "PHL", percentage: "7.8"},
    POL: { fillKey: "POL", percentage: "-  "},
    PRT: { fillKey: "PRT", percentage: "-  "},
    QAT: { fillKey: "QAT", percentage: "0.0"},
    ROU: { fillKey: "ROU", percentage: "-  "},
    RUS: { fillKey: "RUS", percentage: "0.9"},
    RWA: { fillKey: "RWA", percentage: "0.2"},
    KNA: { fillKey: "KNA", percentage: "0.3"},
    SAU: { fillKey: "SAU", percentage: "0.2"},
    SEN: { fillKey: "SEN", percentage: "1.1"},
    SRB: { fillKey: "SRB", percentage: "0.0"},
    SLE: { fillKey: "SLE", percentage: "0.3"},
    SVK: { fillKey: "SVK", percentage: "-  "},
    SVN: { fillKey: "SVN", percentage: "-  "},
    SLB: { fillKey: "SLB", percentage: "0.2"},
    SOM: { fillKey: "SOM", percentage: "6.9"},
    ZAF: { fillKey: "ZAF", percentage: "0.1"},
    ESP: { fillKey: "ESP", percentage: "0.1"},
    LKA: { fillKey: "LKA", percentage: "6.9"},
    SDN: { fillKey: "SDN", percentage: "3.9"},
    SUR: { fillKey: "SUR", percentage: "1.0"},
    SWZ: { fillKey: "SWZ", percentage: "-  "},
    SWE: { fillKey: "SWE", percentage: "0.0"},
    CHE: { fillKey: "CHE", percentage: "0.0"},
    SYR: { fillKey: "SYR", percentage: "2.6"},
    TWN: { fillKey: "TWN", percentage: "0.0"},
    TJK: { fillKey: "TJK", percentage: "0.3"},
    TZA: { fillKey: "TZA", percentage: "0.1"},
    THA: { fillKey: "THA", percentage: "5.7"},
    TGO: { fillKey: "TGO", percentage: "-  "},
    TTO: { fillKey: "TTO", percentage: "-  "},
    TUN: { fillKey: "TUN", percentage: "0.5"},
    TUR: { fillKey: "TUR", percentage: "1.0"},
    TKM: { fillKey: "TKM", percentage: "0.0"},
    UGA: { fillKey: "UGA", percentage: "4.8"},
    UKR: { fillKey: "UKR", percentage: "2.9"},
    ARE: { fillKey: "ARE", percentage: "0.0"},
    GBR: { fillKey: "GBR", percentage: "0.1"},
    USA: { fillKey: "USA", percentage: "0.6"},
    URY: { fillKey: "URY", percentage: "0.0"},
    UZB: { fillKey: "UZB", percentage: "0.2"},
    VUT: { fillKey: "VUT", percentage: "0.1"},
    VEN: { fillKey: "VEN", percentage: "0.1"},
    VNM: { fillKey: "VNM", percentage: "-  "},
    ESH: { fillKey: "ESH", percentage: "-  "},
    YEM: { fillKey: "YEM", percentage: "4.8"},
    ZMB: { fillKey: "ZMB", percentage: "0.1"},
    ZWE: { fillKey: "ZWE", percentage: "0.0"},
    SSD: { fillKey: "SSD", percentage: "19.9"},
    PSE: { fillKey: "PSE", percentage: "0.5"},

    //zoom.bubbles([
     //{name: 'Bubble 1', latitude: 21.32, longitude: -7.32, radius: 45, fillKey: 'gt500'},
     //{name: 'Bubble 2', latitude: 12.32, longitude: 27.32, radius: 25, fillKey: 'eq0'},
     //{name: 'Bubble 3', latitude: 0.32, longitude: 23.32, radius: 35, fillKey: 'lt25'},
     //{name: 'Bubble 4', latitude: -31.32, longitude: 23.32, radius: 55, fillKey: 'eq50'},
    //], {
     //popupTemplate: function(geo, data) {
       //return "<div class='hoverinfo'>Bubble for " + data.name + "";
     //}
    //});


  },
  geographyConfig: {
    popupTemplate: function(geo, data) {
        return ['<div class="hoverinfo"><strong>',
                'Country: ' + geo.properties.name,
                '<br> Deaths per mention ' + data.percentage,
                '</strong></div>'].join('');
    }
  }
});
//Append a linearGradient element to the defs and give it a unique id
//Append a defs (for definition) element to your SVG
var svg = d3.select("#svg_map4").append("svg").attr("id", "map4_legend").attr("width", 370).attr("height", 45);
var defs = svg.append("defs");

//Append a linearGradient element to the defs and give it a unique id
var linearGradient = defs.append("linearGradient")
    .attr("id", "linear-gradient");
    //Set the color for the start (0%)
linearGradient.append("stop")
    .attr("offset", "0%")
    .attr("stop-color", "#f0fff0"); //light blue

//Set the color for the end (100%)
linearGradient.append("stop")
    .attr("offset", "100%")
    .attr("stop-color", "#191970"); //dark blue
//Draw the rectangle and fill with gradient
svg.append("rect")
      .attr("width", 300)
      .attr("height", 13)
      .style("fill", "url(#linear-gradient)");
      var x = d3.scale.linear().range([0, 300]).domain([1, 32]);

			var xAxis = d3.svg.axis().scale(x).orient("bottom");

			svg.append("g").attr("class", "x axis").attr("transform", "translate(0,20)").call(xAxis).append("text").attr("y", 15).attr("dy", ".71em").style("text-anchor", "end").text("axis title");
